logging:
  level: INFO
  loggers:
    com.martinrist: DEBUG

helloWorld:
  template: Hello, %s!
  # To override setting, call java with -Ddw.helloWorld.defaultName=NEWNAME
  # or set the `DW_DEFAULT_NAME` environment variable
  defaultName: ${DW_DEFAULT_NAME:-Stranger}